### PR TITLE
LoRa Security Fix

### LINKED ISSUE #92: LoRa: Exploitable buffer overflow vulnerability in working version of lora_receive
**Describe the bug**
In the working version of lora_receive, a buffer overflow vulnerability is present that would allow stack smashing in the caller. As this is an interface that goes between the inside and outside of the attack surface, this vulnerability is assumed to be (and very likely is) exploitable, as an attacker would have a tremendous amount of control over the data entering this buffer.

The cause of this bug is the dynamic nature of buffer_len_ptr in lora_receive. If the modem has more data in its FIFO than is present in the buffer passed in (for example, the LORA_MSG data structure), then lora_receive will write to an address beyond the length of the buffer, overwriting data.

**To Reproduce**
Transmit more data to the receiver than the size of its message data structure. The likely result will be a hardfault triggered by destruction of a stack canary, although I haven't tested this myself. Worst case scenario, we don't have proper stack canaries and due to the fact that binaries for the flight computer are not position independent, this is a hijackable vulnerability.

I encourage someone at SDR to try to successfully hijack execution either to shellcode or a known address in the binary that can produce a verifiable result (e.g. jump to a location where the led changes color or buzzer beeps) as a proof of concept. If someone can do this, you'll get added to the list of security SMEs (so basically an instant promotion lol). Feel free to disable canaries if they're present to try this out.

**Expected behavior**
The solution for this vulnerability is to simply pass a static buffer size and enforce writes to this buffer staying under this size.

**Screenshots/Pictures/Video**
N/A

**Additional context**
[CWE-121](https://cwe.mitre.org/data/definitions/121.html), [CWE-788](https://cwe.mitre.org/data/definitions/788.html).

For learning purposes, consider taking a look at this module from ASU's cybersecurity faculty: https://pwn.college/intro-to-cybersecurity/binary-exploitation/

**Points of Contact**
LoRa subject matter expert: @266-750Balloons
Security subject matter expert: @ETSells

### PR DESCRIPTION
**Pull request by Bigmouseears**
…er size

## Description
A brief description of the changes in the PR

### Issue Link
Please provide a link to the issue (e.g. "Closes #1"). 

Also, if this PR is one of multiple for this issue, link the parent if this is a child OR link 
the children if this is the parent. Do not use "closes" keywords on child PRs, only use them on 
the parent.

### Testing
- [ ] Passes existing unit tests
- [ ] Unit tests modified (link the test changes as a child PR)
- [ ] Integration test performed

Attach any test artifacts here, if relevant.

### Other
Leave any additional notes here

### Standards
- [ ] Follows FCF Architectural Standards
- [ ] Follows SDR Coding Standards
- [ ] Code complexity/function Size is minimized
- [ ] Code is testable
- [ ] Code is readable and commented properly
- [ ] License terms are respected

### Error Handling
- [ ] Potentially unsafe functions return a status code
- [ ] Error returns properly handled

### Memory
- [ ] Stack allocated memory is scoped correctly
- [ ] Heap allocated memory is avoided
- [ ] Globally allocated memory is minimized except when necessary
- [ ] Pointers are used correctly
- [ ] Concurrency has been considered

### Performance
- [ ] Rate limiters are respected
- [ ] Busy waiting is avoided
- [ ] "Delay" calls are not used in performance sensitive code

### CODE REVIEW

File: lora/lora.c [hunk 1]
```diff
@@ -400,9 +400,15 @@ LORA_STATUS lora_receive_ready() {
 // =============================================================================
 // lora_receive: receive a buffer from lora fifo with continuous mode
 // =============================================================================
-LORA_STATUS lora_receive(uint8_t* buffer_ptr, uint8_t* buffer_len_ptr){
+LORA_STATUS lora_receive(uint8_t* buffer_ptr, uint8_t* buffer_len_ptr, uint8_t* max_buffer_len){
     uint8_t timeout_flag;
 
+    
+    if (*buffer_len_ptr > *max_buffer_len) {
+        return LORA_FAIL;
```
Comment (ETSells) [inline lora/lora.c]: nit: consider adding a new status entry for this particular status (something like `LORA_BUFFER_UNDERSIZED`). This would allow us to detect when this condition occurs in the app/mod layer, and thus we could implement fail-safe handling for this condition.

**Review by ETSells — APPROVED** [review]
LGTM! @266-750Balloons should approve as well since it's his component.

File: lora/lora.c (hunk 1 above)
Comment (Bigmouseears) [reply lora/lora.c]: Oop I think I did add that, I just forgot to commit it. LORA_BUFFER_UNDERSIZED sounds like a better name than what I had originally though

Comment (ETSells) [reply lora/lora.c]: Yeah this looks great to me. Up to @266-750Balloons now.

**Comment by ETSells** [comment]
@266-750Balloons Stale PR: bump.

**Review by 266-750Balloons — APPROVED** [review]
Looks good. Merging. Sorry for taking 50 years to review this.
